### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jappeace** [plt-amy/agda-search#1]
With your approval, I wish to put this on a website. (agda-search.com or whatever), I'll try up streaming said code as well if you want, or refactor this into a library.

**Comment by plt-amy** [comment]
consider it BSD3 for the moment, I'll add the file when I manage to crawl out of bed

**Comment by plt-amy** [comment]
consider it BSD3 for the moment, I'll add the file when I manage to crawl out of bed

**Comment by jappeace** [comment]
solved by https://github.com/plt-amy/agda-search/pull/4
